"""Models package — re-exports all model classes for convenient access."""

from src.ghost_hunter.models.attack_surface import AttackSurfaceEntry, VulnIndicator
from src.ghost_hunter.models.endpoints import (
    Endpoint,
    Finding,
    ParameterDetail,
    SecuritySchemeInfo,
    TechFingerprint,
)
from src.ghost_hunter.models.insights import ScanInsight
from src.ghost_hunter.models.strategy import ScanStrategy
from src.ghost_hunter.models.enums import (
    DiscoverySource,
    EndpointCategory,
    ParamLocation,
    RiskLevel,
    VulnPattern,
)
from src.ghost_hunter.models.scan import AgentResult, ScanState
from src.ghost_hunter.models.llm_responses import (
    APIGuess,
    APIGuessResponse,
    AttackSurfaceItem,
    ClassificationBatchResponse,
    EndpointClassification,
    EndpointHypothesis,
    HypothesisResponse,
    JSAnalysisBatchResponse,
    JSEndpoint,
    PrioritizationBatchResponse,
    ReanalysisRequest,
    HTMLIntelAnalysisResponse,
    HTMLIntelFinding,
    ReconAnalysisResponse,
    ResponseBodyAnalysisResponse,
    ResponseBodyFinding,
    VerifierAction,
    VerifierBatchResponse,
    VulnAnalysisBatchResponse,
    VulnConfidenceAdjustment,
    VulnEndpointAnalysis,
    VulnNewIndicator,
    VulnSuppression,
)

__all__ = [
    "APIGuess",
    "APIGuessResponse",
    "AgentResult",
    "AttackSurfaceEntry",
    "AttackSurfaceItem",
    "ClassificationBatchResponse",
    "DiscoverySource",
    "Endpoint",
    "EndpointCategory",
    "EndpointClassification",
    "EndpointHypothesis",
    "Finding",
    "HTMLIntelAnalysisResponse",
    "HTMLIntelFinding",
    "HypothesisResponse",
    "JSAnalysisBatchResponse",
    "JSEndpoint",
    "ParamLocation",
    "ParameterDetail",
    "PrioritizationBatchResponse",
    "ReanalysisRequest",
    "ReconAnalysisResponse",
    "ResponseBodyAnalysisResponse",
    "ResponseBodyFinding",
    "RiskLevel",
    "ScanInsight",
    "ScanState",
    "ScanStrategy",
    "SecuritySchemeInfo",
    "TechFingerprint",
    "VerifierAction",
    "VerifierBatchResponse",
    "VulnAnalysisBatchResponse",
    "VulnConfidenceAdjustment",
    "VulnEndpointAnalysis",
    "VulnIndicator",
    "VulnNewIndicator",
    "VulnPattern",
    "VulnSuppression",
]
